#!/usr/bin/env python3
"""04_issue_identities.py - Personhood/Entity credentials + 1-of-2 lockboxes (Phase 3).

Producing pathways (generated by this script as templates too):
  - Collaboration.Identity.IssuePersonhoodCredential@v1  (public self-asserted claim + commitment)
  - Collaboration.Identity.SealNameLockbox@v1            (AES-256-CBC/PBKDF2 sealed real identity)
  - Collaboration.Identity.AssertRelationship@v1         (VRC-shaped person<->entity association)

OpenVTC-compatible (PHC/VRC, First Person Protocol, did:key issuer; did:webvh deferred).
Real names + identities come from keys/subjects.private.json (unsealed). Cleartext payloads
are written only to keys/.tmp and shredded; the sealed bundle holds placeholders + ciphertext.

Reveal model (v1): the Originator holds keys/originator-reveal.key (gitignored) and can open
every lockbox (AES-256-CBC, PBKDF2-HMAC-SHA256, 600k iters - openssl + Web Crypto reproducible).
The intended 1-of-2 with the subject's DID key is recorded in recipients[] as the upgrade path.
ZK progressive reveal + FHE are roadmap (see identities/README.md).
"""
import base64
import hashlib
import json
import os
import secrets
import subprocess
from pathlib import Path

SNAP = Path("collaboration/20260528-130500")
IDENT = SNAP / "identities"
KEYS = Path("keys")
REVEAL_KEY = KEYS / "originator-reveal.key"
TMP = KEYS / ".tmp"
RUN_ID = os.environ.get("PATHWAY_RUN_ID", "")
ITER = 600000

cfg = json.loads((KEYS / "subjects.private.json").read_text(encoding="utf-8"))
SUBJECTS = cfg["subjects"]


def ensure_reveal_key() -> None:
    if not REVEAL_KEY.exists():
        REVEAL_KEY.write_bytes(base64.b64encode(secrets.token_bytes(32)))


def seal(payload: dict) -> str:
    TMP.mkdir(parents=True, exist_ok=True)
    pt = TMP / f"pt_{secrets.token_hex(6)}.json"
    pt.write_text(json.dumps(payload), encoding="utf-8")
    try:
        out = subprocess.run(
            ["openssl", "enc", "-aes-256-cbc", "-pbkdf2", "-iter", str(ITER), "-salt",
             "-pass", f"file:{REVEAL_KEY}", "-in", str(pt)],
            check=True, capture_output=True,
        ).stdout
        return base64.b64encode(out).decode("ascii")
    finally:
        # overwrite then remove cleartext
        pt.write_bytes(secrets.token_bytes(len(pt.read_bytes()) or 16))
        pt.unlink(missing_ok=True)


def commitment(real_name: str, salt_hex: str) -> str:
    return hashlib.sha256((real_name + salt_hex).encode("utf-8")).hexdigest()


TEMPLATES = {
    "Collaboration.Identity.IssuePersonhoodCredential.v1.yaml": """# Collaboration.Identity.IssuePersonhoodCredential@v1
pathway_template:
  identity:
    template_id: Collaboration.Identity.IssuePersonhoodCredential@v1
    artifact_type: pathway-template
    triple: { domain: Collaboration, subdomain: Identity, action: IssuePersonhoodCredential }
    version: 1.0.0
  description: |
    Issues a public, self-asserted OpenVTC-compatible Personhood Credential (PHC) for a
    person, or an Entity Credential for an organization: "a real, unique person/entity
    participated". Carries a salted commitment sha256(real_name||salt) binding the public
    claim to the sealed identity, with no real name in the public artifact. Issuer = the
    Originator (did:key; webvh deferred).
  implementation: collaboration-pathways/scripts/04_issue_identities.py
  output: { artifact: personhood_or_entity_credential }
""",
    "Collaboration.Identity.SealNameLockbox.v1.yaml": """# Collaboration.Identity.SealNameLockbox@v1
pathway_template:
  identity:
    template_id: Collaboration.Identity.SealNameLockbox@v1
    artifact_type: pathway-template
    triple: { domain: Collaboration, subdomain: Identity, action: SealNameLockbox }
    version: 1.0.0
  description: |
    Seals a subject's real name + digital identities (DIDs / URLs) into a lockbox encrypted
    AES-256-CBC under PBKDF2-HMAC-SHA256 (600k iters; openssl + Web Crypto reproducible).
    recipients[] records the intended 1-of-2: the Originator (operative now) OR the subject's
    DID key (upgrade path). Enables selective, progressive reveal (ZK + FHE on the roadmap).
  implementation: collaboration-pathways/scripts/04_issue_identities.py
  output: { artifact: name_lockbox }
""",
    "Collaboration.Identity.AssertRelationship.v1.yaml": """# Collaboration.Identity.AssertRelationship@v1
pathway_template:
  identity:
    template_id: Collaboration.Identity.AssertRelationship@v1
    artifact_type: pathway-template
    triple: { domain: Collaboration, subdomain: Identity, action: AssertRelationship }
    version: 1.0.0
  description: |
    Asserts an OpenVTC-compatible Verifiable Relationship Credential (VRC) between a person
    and an entity (representative-of). Allows revealing "at least one representative of the
    entity" or "the entity only" independently, by inference, without counterparty risk.
  implementation: collaboration-pathways/scripts/04_issue_identities.py
  output: { artifact: relationship_credential }
""",
}

README = """# identities/ - de-identification lockboxes (privacy proxy)

Every de-identified placeholder (person-a/b/c, entity-1/2/3) has:
- a public, self-asserted credential (`*.credential.json`) - OpenVTC-compatible PHC (person)
  or Entity Credential, claiming "a real, unique person/entity participated", carrying a
  salted commitment but NO real name; and
- a lockbox (`*.lockbox.json`) - the real name + digital identities (DIDs/URLs), encrypted
  AES-256-CBC / PBKDF2-HMAC-SHA256 (600k iters).

Relationships (`relationships/*.json`) assert person<->entity (representative-of) so a peer
can be vouched for "by inference" (at least one real representative exists) without revealing
who - selective, least-privilege disclosure.

## Reveal (v1)
The Originator holds `keys/originator-reveal.key` (gitignored, never sealed) and can open any
lockbox. The viewer (`viewer/index.html`) reproduces the openssl decryption in-browser via
Web Crypto (PBKDF2 -> AES-CBC). The intended **1-of-2** with each subject's DID key is recorded
in each lockbox `recipients[]` as the upgrade path: once a subject registers/【converts a key,
their slot is wrapped so EITHER party can open it.

## Roadmap (designed-for, not in v1)
- Per-recipient DID key-wrapping (genuine 1-of-2 with subject keys; X25519 from did:key).
- Zero-knowledge progressive reveal (prove "a real person exists" / "represents entity-2"
  without revealing the name); the salted commitment is the first step.
- Fully homomorphic encryption over sealed identity attributes.
""".replace("【", "")


def main() -> int:
    ensure_reveal_key()
    (IDENT / "persons").mkdir(parents=True, exist_ok=True)
    (IDENT / "entities").mkdir(parents=True, exist_ok=True)
    (IDENT / "relationships").mkdir(parents=True, exist_ok=True)
    produced = []

    by_ph = {s["placeholder"]: s for s in SUBJECTS}
    for s in SUBJECTS:
        ph = s["placeholder"]
        if s["kind"] not in ("person", "entity"):
            continue
        sub = "persons" if s["kind"] == "person" else "entities"
        salt = secrets.token_hex(16)
        payload = {
            "real_name": s["real_name"],
            "kind": s["kind"],
            "identities": s.get("identities", []),
            "did": s.get("did"),
            "associated_entity": s.get("associated_entity"),
            "representative": s.get("representative"),
            "salt": salt,
        }
        ct = seal(payload)
        commit = commitment(s["real_name"], salt)
        cred = {
            "@context": "https://www.w3.org/ns/credentials/v2",
            "type": ["VerifiableCredential",
                     "PersonhoodCredential" if s["kind"] == "person" else "EntityCredential"],
            "issuer": "Originator (bundle author; OpenVTC-compatible did:key issuer)",
            "self_asserted": True,
            "subject_placeholder": ph,
            "subject_kind": s["kind"],
            "claim": ("A real, unique person participated in this collaboration lineage."
                      if s["kind"] == "person" else
                      "A real entity participated in this collaboration lineage."),
            "commitment": {"alg": "sha256(real_name||salt)", "value": commit},
            "lockbox": f"identities/{sub}/{ph}.lockbox.json",
            "first_person_protocol": "OpenVTC-compatible PHC/EntityCredential; did:webvh deferred",
            "produced_by_pathway": "Collaboration.Identity.IssuePersonhoodCredential@v1",
            "pathway_run_id": RUN_ID,
        }
        lockbox = {
            "subject_placeholder": ph,
            "kind": s["kind"],
            "reveal": {
                "alg": "aes-256-cbc", "kdf": "pbkdf2-hmac-sha256", "iter": ITER,
                "format": "openssl enc -aes-256-cbc -pbkdf2 -salt (base64)",
                "ciphertext_b64": ct,
            },
            "recipients": [
                {"role": "originator", "method": "originator-reveal-key",
                 "key_ref": "keys/originator-reveal.key", "can_open": True},
                {"role": "subject",
                 "method": "pending_subject_key (1-of-2 upgrade path; subject DID + identity URLs are SEALED in the payload, revealed only on open)",
                 "can_open": False},
            ],
            "commitment": {"alg": "sha256(real_name||salt)", "value": commit, "salt_in_payload": True},
            "produced_by_pathway": "Collaboration.Identity.SealNameLockbox@v1",
            "pathway_run_id": RUN_ID,
        }
        (IDENT / sub / f"{ph}.credential.json").write_text(json.dumps(cred, indent=2) + "\n", encoding="utf-8")
        (IDENT / sub / f"{ph}.lockbox.json").write_text(json.dumps(lockbox, indent=2) + "\n", encoding="utf-8")
        produced += [f"identities/{sub}/{ph}.credential.json", f"identities/{sub}/{ph}.lockbox.json"]

    # relationships (VRC) from person->entity associations
    for s in SUBJECTS:
        if s["kind"] == "person" and s.get("associated_entity"):
            ent = s["associated_entity"]
            rel = {
                "@context": "https://www.w3.org/ns/credentials/v2",
                "type": ["VerifiableCredential", "VerifiableRelationshipCredential"],
                "issuer": "Originator",
                "self_asserted": True,
                "relationship": "represents",
                "person": s["placeholder"],
                "entity": ent,
                "claim": f"{s['placeholder']} is a real representative of {ent}; revealable by inference (at least one representative exists) without naming.",
                "produced_by_pathway": "Collaboration.Identity.AssertRelationship@v1",
                "pathway_run_id": RUN_ID,
            }
            (IDENT / "relationships" / f"{s['placeholder']}-{ent}.json").write_text(
                json.dumps(rel, indent=2) + "\n", encoding="utf-8")
            produced.append(f"identities/relationships/{s['placeholder']}-{ent}.json")

    # templates + readme
    for name, body in TEMPLATES.items():
        (SNAP / "collaboration-pathways" / "pathways" / name).write_text(body, encoding="utf-8")
        produced.append(f"collaboration-pathways/pathways/{name}")
    (IDENT / "README.md").write_text(README, encoding="utf-8")
    produced += ["identities/README.md",
                 f"{SNAP}/collaboration-pathways/scripts/04_issue_identities.py"]
    # normalize produced to snapshot-relative under SNAP for assets indexed at repo level
    produced = [str(SNAP / p) if not p.startswith(str(SNAP)) else p for p in produced]

    print(f"identities: issued {len([s for s in SUBJECTS if s['kind'] in ('person','entity')])} "
          f"credentials+lockboxes; relationships + 3 templates + README written")
    am = os.environ.get("ASSET_MANIFEST")
    if am:
        Path(am).write_text(json.dumps(produced), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
