#!/usr/bin/env python3
"""14_strip_token_followup.py - completes the strip-token step (08) for files it missed.

The 08 strip-token run replaced the legacy org token with its replacement across snapshot
text and run records, but the historical canon-import script retained the legacy token in
its hardcoded source path. This follow-up reconciles every remaining occurrence in the
snapshot - including prior run records that embedded it - so the published bundle carries
none. The token pair is loaded from a PRIVATE, gitignored file so it never appears in this
script's own source (or its sealed run record). Idempotent; stdlib only; no network.

Producing pathway: Collaboration.Refactor.RenameTerm@v1 (token strip, follow-up).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

SNAP = Path("collaboration/20260528-130500")
TOKEN_FILE = Path("keys/.scrub_token.json")

EXTS = {".py", ".md", ".yaml", ".yml", ".json", ".txt", ".html"}
SKIP_DIRS = {"attestations"}  # CONTENT_MANIFEST / BUNDLE_SIGNATURE are regenerated by the seal


def main() -> int:
    pairs = json.loads(TOKEN_FILE.read_text(encoding="utf-8")).get("org_tokens", [])
    if not pairs:
        print("no org_tokens configured; nothing to do")
        return 0

    changed: list[str] = []
    for p in sorted(SNAP.rglob("*")):
        if not p.is_file() or p.suffix not in EXTS:
            continue
        if any(part in SKIP_DIRS for part in p.relative_to(SNAP).parts):
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        new = text
        for old, repl in pairs:
            new = new.replace(old, repl)
        if new != text:
            p.write_text(new, encoding="utf-8")
            changed.append(str(p))
            print(f"scrubbed token in {p}")

    produced = changed + [str(SNAP / "collaboration-pathways" / "scripts" / "14_strip_token_followup.py")]
    am = os.environ.get("ASSET_MANIFEST")
    if am:
        Path(am).write_text(json.dumps(produced), encoding="utf-8")
    print(f"token follow-up: {len(changed)} file(s) reconciled")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
