#!/usr/bin/env python3
"""16_strip_emdash.py - remove the em dash character from authored bundle content.

Replaces every em dash (U+2014) with a hyphen "-" across the snapshot's AUTHORED content.
Deliberately EXCLUDES:
  - canon/        : verbatim, sha256-signed authoritative spec + architecture (must stay intact)
  - pathway-runs/ : immutable provenance records (embedded source + hashes must not be mutated)
  - attestations/ : regenerated by the seal step
Idempotent; stdlib only; no network; no em dash in this source.

Producing pathway: Collaboration.Refactor.RenameTerm@v1 (style normalization).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

SNAP = Path("collaboration/20260528-130500")
EM_DASH = "\u2014"
REPL = "-"
EXTS = {".md", ".yaml", ".yml", ".json", ".txt", ".html", ".py"}
SKIP_DIRS = {"canon", "pathway-runs", "attestations"}


def main() -> int:
    changed: list[str] = []
    for p in sorted(SNAP.rglob("*")):
        if not p.is_file() or p.suffix not in EXTS:
            continue
        if any(part in SKIP_DIRS for part in p.relative_to(SNAP).parts):
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        if EM_DASH in text:
            p.write_text(text.replace(EM_DASH, REPL), encoding="utf-8")
            changed.append(str(p))
            print(f"stripped em dash in {p}")

    produced = changed + [str(SNAP / "collaboration-pathways" / "scripts" / "16_strip_emdash.py")]
    am = os.environ.get("ASSET_MANIFEST")
    if am:
        Path(am).write_text(json.dumps(produced), encoding="utf-8")
    print(f"em dash strip: {len(changed)} file(s) normalized")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
